[package]
name = "light_i_lesson"
version = "0.21.0"
authors = ["taidaesal"]
edition = "2018"

[dependencies]
vulkano = "0.21.0"
winit = "0.24.0"
vulkano-win = "0.21.0"
vulkano-shaders = "0.21.0"
nalgebra-glm = "0.11.0"